### ISSUE TITLE
some error

### ISSUE THREAD

**Issue by rosevinnur** [eGust/manhuagui.flutter#1]
hello
i`m newbie
i got some error
![screen shot 2018-09-11 at 07 51 49](https://user-images.githubusercontent.com/14951753/45338811-d3a07e80-b597-11e8-8999-7d2e20c7c99b.png)

**Comment by eGust** [comment]
plz look into `lib/config.dart`. fyi, this app basically is displaying a chinese comic website. maybe don't waste time on it?
