### ISSUE TITLE
mongodb script

### ISSUE THREAD

**Issue by rosevinnur** [eGust/manhuagui.flutter#2]
please share the sql script for mongo db

**Comment by eGust** [comment]
what do you mean? mongodb is a NoSQL database
this app is designed working well without mongo connection. you can simply ignore it.

**Comment by rosevinnur** [comment]
I mean SQL commands like CREATE TABLE.

**Comment by eGust** [comment]
I don't think you get the point. there is no such thing like `CREATE TABLE` in mongodb. the name of the only collection `comics` is explicitly written in the source and that's all. you'd better have some basic knowledge before asking questions. 
This app only READs data from mongo and does NOT update anything. It's meaningless to connect to an empty db. 
There is a separated script to crawl data and update the db. Apparently, I don't think it's a good idea to open the source, or it'd already be published.
